accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from projects.views import (
    ProjectDetailView,
    ProjectListView,
    ProjectCreateView,
)
from django.urls import path

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from tasks.views import TaskCreateView, TaskListView, TaskUpdateView
from django.urls import path

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("tasks/", include("tasks.urls")),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("admin/", admin.site.urls),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

accounts/models.py
# from django.db import models

# # Create your models here.

projects/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="projects"
    )

    def __str__(self):
        return str(self.name)

tasks/models.py
from django.db import models
from projects.models import Project
from django.conf import settings


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(null=True)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="tasks",
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return str(self.name)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse_lazy


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect(reverse_lazy("home"))
        else:
            form = UserCreationForm()
            context = {"form": form}
            return render(request, "registration/signup.html", context)
    else:
        form = UserCreationForm()
        context = {"form": form}
        return render(request, "registration/signup.html", context)

projects/views.py
# from pprint import pprint
# from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView

from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.db.models import Count

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    # login_url = "/login/"
    model = Project
    template_name = "projects/list.html"
    print("huh")

    def get_queryset(self):
        print(Project.tasks)
        # pprint(dir(Project.tasks.all))
        return Project.objects.filter(members=self.request.user)

    def get_context_data(self, **kwarg):
        context = super().get_context_data(**kwarg)
        context["taskcontext"] = Project.objects.annotate(
            number_of_tasks=Count("tasks")
        )
        return context


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/details.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "members", "description"]

    def form_valid(self, form):
        form.instance.account = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("show_project", kwargs={"pk": self.object.pk})

tasks/views.py
# from django.shortcuts import render


from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from tasks.models import Task
from django.urls import reverse_lazy, reverse


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        print(self.object)
        return reverse("show_project", kwargs={"pk": self.object.project.pk})


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"
    context_object_name = "tasklistname"

    def get_queryset(self):
        print(Task.objects.filter(assignee=self.request.user))
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>project bro</title>
    </head>

    <body>
        <header>

            <nav>

                {% if user.is_authenticated %}
                    <ul>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        <li><a href="{% url 'list_projects' %}">My projects</a></li>
                        <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
                    </ul>
                {% else %}
                    <li><a href="{% url 'login' %}">logout</a></li>
                    <li><a href="{% url 'signup' %}">signup</a></li>
                {% endif %}


            </nav>

        </header>

        {% block content %}
        {% endblock content %}
    </body>

</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}


    <main>
        <div>
            <h1>Create a new project</h1>





            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create</button>
            </form>



        </div>
    </main>

{% endblock content %}

projects/templates/projects/details.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}


    <main>
        <div>
            <h1>{{project.name}}</h1>
            {{ project.description|markdownify }}
            <h2>Tasks</h2>
            <a href="{% url 'create_task'%}">Create a new task</a>
            {% if project.tasks.all%}

                <table>
                    <tr>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>

                    </tr>
                    {% for task in project.tasks.all %}
                        <tr>
                            <td>{{task.name}}</td>
                            <td>{{task.assignee}}</td>
                            <td>{{task.start_date}}</td>
                            <td>{{task.due_date}}</td>
                            <td>{{task.is_completed}}</td>
                        </tr>
                    {% endfor %}
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}
        </table>
    </div>
    </main>

{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block content %}
    <nav>
        {% if user.is_authenticated %}
            <a href="{% url 'create_project' %}">Create a project</a>
        {% endif %}
        <a href="{% url 'create_task' %}">Create a task</a>

        <a href="{% url 'show_my_tasks' %}"> Your tasks</a>
    </nav>


    <main>
        <div>
            <h1>My Projects</h1>

            {% if not project_list %}
                <p>You are not assigned to any projects</p>
                </div>
            {% else %}
                <table>
                    <tr>
                        <th>Name</th>
                        <th>Number of tasks</th>
                    </tr>
                    {% for project in taskcontext %}
                        <tr>

                            <td><a href="{% url 'show_project' project.pk%}"> {{project.name}}</a></td>
                            <td>{{project.number_of_tasks}}</td>
                        </tr>
                    {% endfor %}
            {% endif %}
        </table>
    </main>

{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}


    <main>
        <div>
            <h1>Create a new task</h1>





            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create</button>
            </form>



        </div>
    </main>

{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block content %}


    <main>
        <div>
            <h1>My Tasks</h1>

            {% if object_list %}

                <table>
                    <tr>
                        <th>Name</th>
                        <th>Start date</th>
                        <th>End Date</th>
                        <th>Is completed</th>

                    </tr>
                    {% for task in object_list %}
                        <tr>
                            <td>{{task.name}}</td>
                            <td>{{task.start_date}}</td>
                            <td>{{task.due_date}}</td>
                            {% if task.is_completed %}
                                <td>Done</td>
                            {% else %}
                                <td>
                                    <form method="post" action="{% url 'complete_task' task.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </table>
    </div>
    </main>
{% endblock content %}